---
- name: Install packages
  hosts: all
  become: true

  tasks:
    - name: Update cache
      apt:
        update_cache: yes

    - name: Upgarde
      apt:
        upgrade: yes

    - name: Set a hostname
      hostname:
        name: "{{ hostname }}"
        use: systemd

    - name: Set timezone using shell
      shell: timedatectl set-timezone Europe/Moscow

#Asia/Tokyo
    # - name: Set timezone to Europe/Moscow
    #   ansible.posix.timezone:
    #     name: Europe/Moscow