---
- name: Install server-1C
  hosts: all
  become: true

  tasks:
    - name: Mount ephemeral SMB volume
      ansible.posix.mount:
        src: //10.10.2.10/repo
        path: /mnt/repo
        opts: "rw,vers=3,file_mode=0766,dir_mode=0766,username={{ ad_username }},password={{ ad_password }}"
        opts_no_log: true
        fstype: cifs
        state: ephemeral

    # -name: Find the arh 