---
- name: Install packages
  hosts: "{{ target_ip }}"
  become: true

  tasks:
    - name: Update cache
      apt:
        update_cache: yes

    - name: Upgarde
      apt:
        upgrade: yes

    - name: Set a hostname
      hostname:
        name: "{{ hostname }}"
        use: systemd

#Asia/Tokyo
    - name: Set timezone to Europe/Moscow
      become: true
      timezone:
        name: Europe/Moscow