---
- name: Install server-1C
  hosts: all
  become: true

  tasks:
    - name: Setup
      setup:

    - name: Check if file exists using stat module
      stat:
        path: /usr/local/bin/oneget
      register: file_status
    - name: Install, configure repository postgrespro
      when: file_status.stat.exists == false
      block:
      - name: Unarchive a file that needs to be downloaded (added in 2.0)
        ansible.builtin.unarchive:
          src: https://github.com/v8platform/oneget/releases/download/v0.6.0/oneget_Linux_x86_64.tar.gz
          dest: /usr/local/bin
          remote_src: yes

    - name: Mount ephemeral SMB volume
      ansible.posix.mount:
        src: //10.10.2.10/repo
        path: /mnt/repo
        opts: "rw,vers=3,file_mode=0766,dir_mode=0767,username={{ ad_username }},password={{ ad_password }}"
        opts_no_log: true
        fstype: cifs
        state: ephemeral

    # - name: Download 1C release {{ v_release }}
    #   environment:
    #     ONEC_USERNAME: "{{ login_1c }}" 
    #     ONEC_PASSWORD: "{{ password_1c }}"
    #   shell: oneget get --path /mnt/repo/ platform:linux.full.x64@{{ v_release }}


    - name: Find a file by name
      find:
        paths: /mnt/repo/platform83/{{ v_release }}
        patterns: "server64_8_3_*"
        recurse: yes
      register: found_files
    - name: Extract only paths
      set_fact:
        file_paths: "{{ found_files.files | map(attribute='path') | list }}"

    - name: Copy file
      ansible.builtin.copy:
        content: "{{ file_paths | join('\n') }}"
        dest: /home/{{ ansible_facts['env']['SUDO_USER'] }}/server64.zip
        owner: "{{ ansible_facts['env']['SUDO_USER'] }}"
        group: "{{ ansible_facts['env']['SUDO_USER'] }}"
        mode: '0777'

    - name: Unmount a mounted volume
      ansible.posix.mount:
        path: /mnt/repo
        state: unmounted

    - name: —Åreate directory
      file:
        path=/home/{{ ansible_facts['env']['SUDO_USER'] }}/server/
        state=directory

    - name: Unarchive Server 1C
      ansible.builtin.unarchive:
        src: /home/{{ ansible_facts['env']['SUDO_USER'] }}/server64.zip
        dest: /home/{{ ansible_facts['env']['SUDO_USER'] }}/server/
        remote_src: yes