---
- name: Install packages
  hosts: "{{ target_ip }}"
  become: true

  tasks:
    - name: Register an example variable
      become: false
      shell: echo "$USER"
      register: username

    - name: Download pgpro-repo-add.sh
      ansible.builtin.get_url:
        url: https://repo.postgrespro.ru/1c/1c-16/keys/pgpro-repo-add.sh
        dest: /home/"{{ $USER }}"
        mode: '751'    