---
- name: Install packages
  hosts: "{{ target_ip }}"
  become: true

  tasks:
    - name: Register an example variable
      become: false
      shell: echo "$USER"
      register: username

    - name: Download pgpro-repo-add.sh
      get_url:
        url: https://repo.postgrespro.ru/1c/1c-16/keys/pgpro-repo-add.sh
        dest: /home/{{ username.stdout }}/
        mode: '0751'

    - name: Run script add repository
      script: /home/diadmin/pgpro-repo-add.sh
      args:
        executable: /bin/bash

    - name: Update cache
      apt:
        update_cache: yes

    - name: Install postgrespro-1c-16
      package:
        name: postgrespro-1c-16
        state: present