---
- name: Install packages
  hosts: all
  become: true

  tasks:

    - name: Setup
      debug:
        msg: The distribution is {{ ansible_distribution }} 
            version {{ ansible_distribution_version }}
            famely {{ ansible_os_family }}.

    - name: Update cache, upgrade and install package is famely Debian
      when: ansible_os_family == "Debian"
      block:
      - name: Update cache
        apt:
          update_cache: yes
      - name: Upgarde
        apt:
          upgrade: yes
      - name: Install packages
        ansible.builtin.package:
          name: "{{ packages }}"
          state: present

    - name: Update cache, upgrade and install package is famely RedHat
      when: ansible_os_family == "RedHat"
      block:
        - name: Upgrade all packages
          ansible.builtin.dnf:
            name: "*"
            state: latest
        - name: Install packages
          ansible.builtin.package:
            name: "{{ packages }}"
            state: present

    - name: Set a hostname
      hostname:
        name: "{{ hostname }}"
        use: systemd

    - name: Set timezone using shell
      shell: timedatectl set-timezone Europe/Moscow


#Asia/Tokyo
    # - name: Set timezone to Europe/Moscow
    #   ansible.posix.timezone:
    #     name: Europe/Moscow