---
- name: Install packages
  hosts: all
  become: true

  tasks:

    - name: Setup
      debug:
        msg: The distribution is {{ ansible_distribution }} 
            version {{ ansible_distribution_version }}
            famely {{ ansible_os_family }}.

    - name: Update cache
      apt:
        update_cache: yes

    - name: Upgarde
      apt:
        upgrade: yes

    - name: Set a hostname
      hostname:
        name: "{{ hostname }}"
        use: systemd

    - name: Set timezone using shell
      shell: timedatectl set-timezone Europe/Moscow

    - name: Install packages
      apt:
        name: "{{ packages }}"
        state: present

#Asia/Tokyo
    # - name: Set timezone to Europe/Moscow
    #   ansible.posix.timezone:
    #     name: Europe/Moscow