---
- name: Install server-1C
  hosts: all
  become: true

  tasks:

    - name: Setup
      # become: false
      setup:
        filter: ansible_env
      register: setup_var

    - name: Print file status
      debug:
        var: setup_var

    - name: Check if file exists using stat module
      stat:
        path: /usr/local/bin/oneget
      register: file_status
    - name: Install, configure repository postgrespro
      when: file_status.stat.exists == false
      block:
      - name: Unarchive a file that needs to be downloaded (added in 2.0)
        ansible.builtin.unarchive:
          src: https://github.com/v8platform/oneget/releases/download/v0.6.0/oneget_Linux_x86_64.tar.gz
          dest: /usr/local/bin
          remote_src: yes

    - name: Mount ephemeral SMB volume
      ansible.posix.mount:
        src: //10.10.2.10/repo
        path: /mnt/repo
        opts: "rw,vers=3,file_mode=0766,dir_mode=0767,username={{ ad_username }},password={{ ad_password }}"
        opts_no_log: true
        fstype: cifs
        state: ephemeral

    - name: Download 1C release {{ v_release }}
      environment:
        ONEC_USERNAME: "{{ login_1c }}" 
        ONEC_PASSWORD: "{{ password_1c }}"
      shell: oneget get --path /mnt/repo/ platform:linux.full.x64@{{ v_release }}