---
- name: Install server-1C
  hosts: all
  become: true

  tasks:

    - name: Export variable to the system
      shell: |
        export ONEC_USERNAME={{ login_1c }}
        export ONEC_PASSWORD={{ password_1c }}

    - name: Mount ephemeral SMB volume
      ansible.posix.mount:
        src: //10.10.2.10/repo
        path: /mnt/repo
        opts: "rw,vers=3,file_mode=0766,dir_mode=0767,username={{ ad_username }},password={{ ad_password }}"
        opts_no_log: true
        fstype: cifs
        state: ephemeral

    # - name: Download OneGet
    #   get_url:
    #     url: https://github.com/v8platform/oneget/releases/download/v0.6.0/oneget_Linux_x86_64.tar.gz
    #     dest: /home/diadmin
    #     mode: '0770'

    - name: Unarchive a file that needs to be downloaded (added in 2.0)
      ansible.builtin.unarchive:
        src: https://github.com/v8platform/oneget/releases/download/v0.6.0/oneget_Linux_x86_64.tar.gz
        dest: /usr/local/bin
        remote_src: yes

    -  name: Download 1C release {{ v_release }}
       shell: oneget get --path /mnt/repo/ platform:linux.full.x64@{{ v_release }}