---
- name: Create Template
  hosts: all
  become: true

  tasks:
    - name: Select {{ vm_id }}
      shell: qm list | awk '{print $1}' | grep {{ vm_id }}
      ignore_errors: yes
      register: search_vm_id

    - name: version {{ vm_id }}
      debug:
        msg: "{{ search_vm_id }}"

    - name: Download Ubuntu Server 24.04 LTS (Noble Numbat) 
      when: search_vm_id.rc != 0
      block:
      - name: Setup
        setup:
      - name: Check if file exists Ubuntu image
        stat:
          path: /var/lib/vz/template/iso/noble-server-cloudimg-amd64.img
        register: file_status
      - name: Install, configure repository postgrespro
        when: file_status.stat.exists == false
        block:
        - name: Download Ubuntu Server 24.04
          ansible.builtin.get_url:
            url: https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img
            dest: /var/lib/vz/template/iso/noble-server-cloudimg-amd64.img
            mode: '0640'
      - name: Create VM {{ vm_id }}
        shell: qm create {{ vm_id }} --memory 2048 --net0 virtio,bridge=vmbr0 --scsihw virtio-scsi-single --machine q35 --cpu x86-64-v3 --cores 2 && \
               qm set {{ vm_id }} --scsi0 local-lvm:0,import-from=/var/lib/vz/template/iso/noble-server-cloudimg-amd64.img,discard=on,ssd=1,iothread=1 && \
               qm set {{ vm_id }} --ide2 local-lvm:cloudinit && \
               qm set {{ vm_id }} --boot order=scsi0 --agent 1 --ostype l26 && \
               qm set {{ vm_id }} --ciuser diadmin --cipassword '123Qwe!@' --sshkeys /root/.ssh/id_rsa_vbitadmin.pub --ipconfig0 ip=dhcp --ciupgrade false && \
               qm resize {{ vm_id }} scsi0 +512M
               qm template {{ vm_id }}





