#cloud-config
users:
  - name: ${ssh_username}
    passwd: ${ssh_passwd}
    ssh-authorized-keys:
      - ssh-rsa ${public_key}
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    groups: sudo
    shell: /bin/bash
timezone: Europe/Moscow
locale: ru_RU.UTF-8
packages:
  - tree