---
- name: Uninstall server-1C
  hosts: all
  become: true

  tasks:
    - name: Search version 1C 
      shell: sudo  systemctl list-units --type=service --state=running | grep srv1cv8 | cut -d ' ' -f 10 | tr -d '(-)'
      register: search_version

    - name: version
      debug:
        msg: "{{ search_version.stdout }}"

    - name: Unistal server 1C 
      shell: "sudo  /opt/1cv8/x86_64/{{ search_version.stdout }}/uninstaller-full --mode unattended"