---
- name: Install server-1C
  hosts: all
  become: true
  vars:
    path_setup: server
    #ansible_become_password: {{ sudo_password }}

  tasks:
    - name: Setup
      setup:
    - name: Check if file exists OneGet
      stat:
        path: /usr/local/bin/oneget
      register: file_status
    - name: Install, configure repository postgrespro
      when: file_status.stat.exists == false
      block:
      - name: Download OneGet
        ansible.builtin.unarchive:
          src: https://github.com/v8platform/oneget/releases/download/v0.6.0/oneget_Linux_x86_64.tar.gz
          dest: /usr/local/bin
          remote_src: yes

    - name: Download 1C release {{ v_release }}
      environment:
        ONEC_USERNAME: "{{ login_1c }}" 
        ONEC_PASSWORD: "{{ password_1c }}"
      shell: oneget get --path /home/{{ ansible_facts['env']['SUDO_USER'] }}/ platform:linux.full.x64@{{ v_release }}

    - name: Find a file server {{ v_release }}
      find:
        paths: /home/{{ ansible_facts['env']['SUDO_USER'] }}/platform83/{{ v_release }}/
        patterns: "server64_8_3_*"
        recurse: yes
      register: found_files
    - name: Extract only paths
      set_fact:
        file_paths: "{{ found_files.files | map(attribute='path') | list }}"

    - name: —Åreate directory {{ path_setup }}
      file:
        path=/home/{{ ansible_facts['env']['SUDO_USER'] }}/{{ path_setup }}/
        state=directory

    - name: Unarchive Server 1C {{ file_paths | join('\n') }}
      ansible.builtin.unarchive:
        src: "{{ file_paths | join('\n') }}"
        dest: /home/{{ ansible_facts['env']['SUDO_USER'] }}/{{ path_setup }}/
        remote_src: yes

    - name: Find a file server 1c {{ v_release }}
      find:
        paths: /home/{{ ansible_facts['env']['SUDO_USER'] }}/{{ path_setup }}
        patterns: "setup-full*"
        recurse: yes
      register: found_files_server
    - name: Extract only paths
      set_fact:
        setup_paths: "{{ found_files_server.files | map(attribute='path') | list }}"

    - name: Install server 1C {{ v_release }}
      shell: "{{ setup_paths | join('\n') }} --mode unattended --enable-components server,ws"

    - name: Recursively remove directory
      ansible.builtin.file:
        path: /home/{{ ansible_facts['env']['SUDO_USER'] }}/{{ path_setup }}
        state: absent

    - name: Change file ownership, group and permissions
      ansible.builtin.file:
        path: /opt/1cv8
        owner: usr1cv8
        group: grp1cv8
        recurse: yes

    - name: Create a symlink for service 1c
      file:
        src: /opt/1cv8/x86_64/{{ v_release }}/srv1cv8-{{ v_release }}@.service
        dest: /etc/systemd/system/srv1cv8-{{ v_release }}@.service
        state: link

    - name: Enable service 1c
      systemd:
        daemon_reload: true
        name: srv1cv8-{{ v_release }}@.service
        enabled: yes
        
    - name: Start service 1c
      ansible.builtin.systemd_service:
        state: started
        name: srv1cv8-{{ v_release }}@default.service